<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastColoredTextBox.Net6" Version="1.0.0" />
    <PackageReference Include="System.Data.OleDb" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DefaultPlugin\DefaultPlugin.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="db_example.accdb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="db_example.laccdb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
	
  <Target Name="CopyPlugins" AfterTargets="Build">
    <ItemGroup>
      <PluginFiles Include="$(SolutionDir)Plugins\DefaultPlugin.dll" />
    </ItemGroup>
    <Copy SourceFiles="@(PluginFiles)" DestinationFolder="$(OutputPath)Plugins\" />
  </Target>

</Project>